version: '3'
services:
  fastapi:
    build:
      context: .
    ports:
      - "8004:80"
  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  etl:
    container_name: elt-proccess
    build:
      context: ./postgres_to_es
    depends_on:
      - elasticsearch
